language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    group: edge
    python: 2.7
  - os: linux
    dist: trusty
    sudo: required
    group: edge
    python: 3.4
  - os: osx
    osx_image: xcode8.1
    language: generic
    env: PYTHONPATH=/Library/Python/2.7/site-packages/
before_install:
  - if test ${TRAVIS_OS_NAME} = "linux"; then sudo apt-get update && sudo apt-mark hold oracle-java9-installer postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 postgresql-client postgresql-client-common postgresql-common postgresql-contrib-9.2 postgresql-contrib-9.3 postgresql-contrib-9.4 postgresql-contrib-9.5 postgresql-contrib-9.6 postgresql-doc && sudo apt-get --fix-missing -o Dpkg::Options::="--force-confold" upgrade -y; fi
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew update && brew unlink openssl && brew link --force openssl; fi
install:
  - ./config/travis/install.sh
script:
  - if test ${TRAVIS_OS_NAME} = "osx"; then PYTHONPATH=/Library/Python/2.7/site-packages/ /usr/bin/python ./run_tests.py; elif test ${TRAVIS_OS_NAME} = "linux"; then if test ${TRAVIS_PYTHON_VERSION} = "2.7"; then coverage run --source=l2tdevtools --omit="*_test*,*__init__*,*test_lib*" ./run_tests.py; else ./run_tests.py; fi; fi
after_success:
  - if test ${TRAVIS_OS_NAME} = "linux" && test ${TRAVIS_PYTHON_VERSION} = "2.7"; then coveralls --verbose; fi
